language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging

  #udagram-api-feed
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed vinhpham95/udagram-api-feed:v1

  #udagram-api-user
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user vinhpham95/udagram-api-user:v1

  #udagram-frontend
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend vinhpham95/udagram-frontend:v1

  #udagram-reverseproxy
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-reverseproxy vinhpham95/udagram-reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push vinhpham95/udagram-api-feed:v1
  - docker push vinhpham95/udagram-api-user:v1
  - docker push vinhpham95/udagram-frontend:v1
  - docker push vinhpham95/udagram-reverseproxy:v1